# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Release

steps:  
  #- script: echo $(projectName) 
  - task: AzureResourceManagerTemplateDeployment@3  
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'AzureRmPipeline-conn'
      subscriptionId: '2e10606a-6ad7-4bad-9222-e3efba853b0b'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'AzureRmPipeline-rg'
      location: 'East US'
      templateLocation: 'Linked artifact'
      csmFile: 'ImportSQLBACPAC/azuredeploy.json'
      #csmParametersFile for dirs KeyVault
      #csmParametersFile: 'ARMExtension/azuredeploy.parameters.json'
      #overrideParameters: '-projectName $(projectName) -linkedTemplateUri  $(urlLinkedTemplate)'
      #overrideParameters: '-adminUsername $(adminUsername) -dnsLabelPrefix $(dnsLabelPrefix)'
      #overrideParameters: '-identityId $(identityId) -keyVaultName $(keyVaultName) -objectId $(adUserId)'
      #overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword) -dnsLabelPrefix $(dnsLabelPrefix)'
      #overrideParameters: 'for KeyVault it will use csmParameters'
      overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword) -storageAccountKey $(storageAccountKey) -bacpacUrl $(bacpacUrl)'
      deploymentMode: 'Incremental'
      deploymentName: 'DeployPipelineTemplate'
      addSpnToEnvironment: true
  